### ISSUE TITLE
Extension of CI to real robots

### ISSUE THREAD

**Issue by universecoder** [jsk-ros-pkg/jsk_travis#326]
How does one extend this utility to carry out tests on real robots after the code build and tests are successful? How would one go about doing this in general, and what tools would be used for motion capture and movement detection? Also, what exact steps would have to be taken to develop this? How is the system diagram extended?

As suggested by you, I have triggered the builds once on your travis and jenkins servers by editing the my forked jsk_travis repository and have understood the code there as well.

**Comment by k-okada** [comment]
> How does one extend this utility to carry out tests on real robots after
the code build and tests are successful? How would one go about doing this
in general,

send job to jenkins machine that connected to real robot

> and what tools would be used for motion capture and movement detection?

For time being, use encoder values to detect the motion of the robot

> Also, what exact steps would have to be taken to develop this? How is the
system diagram extended?


1. connect jenkins job to your local mchine
2. instead of running docker, use native environment to build source
3. instead of running within simulator, running code with real robot
4. extent test case for real robot testing, for example the robot move back
to reset(initial) pose/position after test.

--
◉ Kei Okada


2017-03-29 22:53 GMT+09:00 Pranav Deshpande <notifications@github.com>:

**Comment by universecoder** [comment]
Thank you! I had thought of the above already but I thought that you were asking for the exact technical details. I have mentioned something similar in my project proposal and will now add what you are saying as well.
