### ISSUE TITLE
Meaning of TARGET_PKGS env

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_travis#328]
There seems no use of `TARGET_PKGS` in scripts.
https://github.com/jsk-ros-pkg/jsk_travis/search?utf8=%E2%9C%93&q=target_pkgs&type=

What is it for?

**Comment by wkentaro** [comment]
I found a case:

https://github.com/jsk-ros-pkg/jsk_travis/blob/0906fac73da2f891e531dff340c8ce37278c25c7/travis.sh#L275

`TARGET_PKGS` is set to `TEST_PKGS` if it is empty.

**Comment by wkentaro** [comment]
I expect `TARGET_PKGS` is passed to `catkin build`, but the change causes different behavior compared the current.

**Comment by wkentaro** [comment]
I tried `CATKIN_TOOLS_BUILD_OPTIONS="$TARGET_PKGS"` and `BUILD_PKGS="$TARGET_PKGS"` in .travis.yaml (both `"` and `'`) but it does not work.

**Comment by wkentaro** [comment]
So, #329 is my solution.

**Comment by k-okada** [comment]
TARGET_PKGS variables is mainly used within the source code, which is a list of packages that is actually compilable with catkin tools, 
this happens in `--install` test cases, which we copy test file with following command
https://github.com/jsk-ros-pkg/jsk_travis/blob/0906fac73da2f891e531dff340c8ce37278c25c7/travis.sh#L329
```
      rostest_files=$(test ! -d install/share/$pkg  || find install/share/$pkg -iname '*.test')
```
for example, if we have package with CATKIN_IGNORE, we want to skip that from test packages.

```
CATKIN_TOOLS_BUILD_OPTIONS="$TARGET_PKGS"
```
may not work because `$` will be eval-ed.

**Comment by wkentaro** [comment]
I see. Thanks.
